insert into `country`(`id`, `capital`, `currency`, `name`) VALUES
(1, 'Nuku\'alofa', 'Euro', 'Cyprus'),
(2, 'Bangui', 'Rand', 'Congo'),
(3, 'Saipan', 'New Zealand Dollar', 'Portugal'),
(4, 'Abu Dhabi', 'Danish Krone', 'San Marino'),
(5, 'Noumea', 'Pound Sterling', 'Namibia'),
(6, 'Saint-Pierre', 'Indian Rupee', 'Yemen'),
(7, 'Brussels', 'US Dollar', 'Egypt'),
(8, 'Zagreb', 'Forint', 'Denmark'),
(10, 'Nouakchott', 'UAE Dirham', 'Saint Kitts and Nevis'),
(11, 'Harare', 'Peso Convertible', 'Italy'),
(12, 'Yerevan', 'Mvdol', 'Nauru'),
(13, 'Avarua', 'Uganda Shilling', 'Ireland'),
(14, 'Luanda', 'Euro', 'Czechia'),
(15, 'Adamstown', 'Sudanese Pound', 'Syrian Arab Republic'),
(17, 'San Juan', 'Tenge', 'Finland'),
(18, 'George Town', 'Boliviano', 'Cabo Verde'),
(19, 'Bandar Seri Begawan', 'Philippine Peso', 'Austria'),
(20, 'Manama', 'Lek', 'Samoa'),
(22, 'Khartoum', 'Afghani', 'Barbados'),
(23, 'Juba', 'Surinam Dollar', 'Singapore'),
(24, 'Seoul', 'East Caribbean Dollar', 'South Africa'),
(25, 'Lisbon', 'Trinidad and Tobago Dollar', 'Burundi'),
(26, 'Tehran', 'Guarani', 'Mauritius'),
(27, 'Bridgetown', 'WIR Franc', 'Russian Federation'),
(29, 'Melekeok', 'Rial Omani', 'Hungary'),
(30, 'Vienna', 'Danish Krone', 'Thailand'),
(31, 'Bamako', 'Qatari Rial', 'Central African Republic'),
(32, 'Papeete', 'SDR (Special Drawing Right)', 'Bahamas'),
(33, 'Majuro', 'US Dollar', 'Poland'),
(34, 'Sarajevo', 'Mexican Unidad de Inversion (UDI)', 'Philippines'),
(35, 'Baghdad', 'US Dollar', 'Togo'),
(36, 'Road Town', 'Bahamian Dollar', 'Canada'),
(37, 'Montevideo', 'CFA Franc BCEAO', 'Serbia'),
(38, 'Maputo', 'US Dollar', 'Bhutan'),
(41, 'Singapore', 'Chilean Peso', 'Jordan'),
(42, 'Tripoli', 'Seychelles Rupee', 'Brunei Darussalam'),
(45, 'Nassau', 'Pound Sterling', 'Panama'),
(46, 'Bogota', 'Convertible Mark', 'Trinidad and Tobago'),
(49, 'San Salvador', 'Zimbabwe Dollar', 'Ethiopia'),
(51, 'Moscow', 'Euro', 'Madagascar'),
(52, 'Ulaanbaatar', 'Dong', 'Benin'),
(53, 'Bujumbura', 'Burundi Franc', 'Saint Vincent and the Grenadines'),
(55, 'Luxembourg', 'Tenge', 'Korea (Democratic People\'s Republic of)'),
(58, 'Riyadh', 'Turkmenistan New Manat', 'Pakistan'),
(59, 'Apia', 'US Dollar', 'Liechtenstein'),
(60, 'Santiago', 'Yemeni Rial', 'Antigua and Barbuda'),
(61, 'Skopje', 'Sri Lanka Rupee', 'Eritrea'),
(64, 'West Island', 'El Salvador Colon', 'Georgia'),
(65, 'Lilongwe', 'Australian Dollar', 'Bosnia and Herzegovina'),
(66, 'North Nicosia', 'Lilangeni', 'Congo, Democratic Republic of the'),
(67, 'Kyiv', 'Somali Shilling', 'Nigeria'),
(70, 'Ljubljana', 'New Zealand Dollar', 'Dominican Republic'),
(71, 'Ankara', 'Taka', 'Tajikistan'),
(72, 'Baku', 'Malagasy Ariary', 'Papua New Guinea'),
(76, 'Beijing', 'Romanian Leu', 'Slovakia'),
(78, 'Madrid', 'Euro', 'Kyrgyzstan'),
(79, 'Stockholm', 'Liberian Dollar', 'Qatar'),
(82, 'Hanoi', 'Euro', 'Gabon'),
(83, 'Pretoria', 'Gourde', 'Ghana'),
(84, 'Mata-Utu', 'US Dollar', 'Venezuela (Bolivarian Republic of)'),
(85, 'Lima', 'Afghani', 'Guinea'),
(87, 'Lusaka', 'Euro', 'India'),
(89, 'Abuja', 'Yemeni Rial', 'Guatemala'),
(91, 'Honiara', 'CFA Franc BCEAO', 'Oman'),
(92, 'Kathmandu', 'Australian Dollar', 'Belize'),
(95, 'Damascus', 'Dong', 'Timor-Leste'),
(97, 'Prague', 'Danish Krone', 'Iraq'),
(98, 'Banjul', 'Uruguay Peso en Unidades Indexadas (UI)', 'Bolivia (Plurinational State of)'),
(101, 'The Settlement', 'US Dollar', 'Germany'),
(104, 'Freetown', 'US Dollar', 'Vanuatu'),
(105, 'Pyongyang', 'Euro', 'Albania'),
(106, 'Tunis', 'WIR Euro', 'Saudi Arabia'),
(107, 'Djibouti', 'Unidad Previsional', 'Jamaica'),
(109, 'Dushanbe', 'Euro', 'Sweden'),
(111, 'Dhaka', 'Danish Krone', 'Malawi'),
(112, 'Malabo', 'Euro', 'Spain'),
(113, 'San Jose', 'Unidad Previsional', 'Palau'),
(115, 'Kinshasa', 'US Dollar', 'Croatia'),
(117, 'Hamilton', 'Pound Sterling', 'France'),
(118, 'Tirana', 'Euro', 'Kazakhstan'),
(119, 'Victoria', 'Mvdol', 'Azerbaijan'),
(120, 'Belgrade', 'Serbian Dinar', 'Tonga'),
(126, 'Nicosia', 'Uzbekistan Sum', 'Lebanon'),
(128, 'Belmopan', 'Moroccan Dirham', 'Mozambique'),
(130, 'Pristina', 'Leone', 'Nepal'),
(135, 'Atafu', 'New Taiwan Dollar', 'Switzerland'),
(137, 'Tarawa', 'Australian Dollar', 'Eswatini'),
(140, 'Nuuk', 'Armenian Dram', 'Micronesia (Federated States of)'),
(145, 'Yaounde', 'East Caribbean Dollar', 'Haiti'),
(149, 'Maseru', 'Yen', 'Mongolia'),
(151, 'Charlotte Amalie', 'Bahraini Dinar', 'Afghanistan'),
(152, 'Moroni', 'East Caribbean Dollar', 'Latvia'),
(156, 'King Edward Point', 'Syrian Pound', 'Botswana'),
(158, 'Tegucigalpa', 'Syrian Pound', 'Sierra Leone'),
(162, 'Taipei', 'East Caribbean Dollar', 'Korea, Republic of'),
(165, 'Amman', 'Kenyan Shilling', 'Monaco'),
(168, 'Lome', 'Peso Uruguayo', 'Mexico'),
(170, 'Philipsburg', 'Forint', 'Guyana'),
(171, 'Monaco', 'CFP Franc', 'United Kingdom of Great Britain and Northern Ireland'),
(172, 'London', 'CFA Franc BCEAO', 'Netherlands');